# Generated by Django 4.1.4 on 2022-12-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=100)),
                ('Mdesc', models.CharField(max_length=300)),
                ('isPublished', models.BooleanField(default=True)),
                ('Mdate', models.DateField(auto_now_add=True)),
                ('Splatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='watchlist.streamingplatform')),
            ],
        ),
    ]
